- name: create compose config folder
  file: path={{docker_compose_path}} mode=755 state=directory

- name: create visualizer compose template
  template: src=visualizer.yml dest={{docker_compose_path}}/visualizer.yml
  register: compose_template

- name: deploy visualizer stack
  command: docker stack deploy -c {{docker_compose_path}}/visualizer.yml visualizer
  register: visualizer_exec
  when:
    - inventory_hostname == docker_swarm_primary_manager
    - compose_template.changed

- debug: var=visualizer_exec
